name: PR build Quarkus images for smoke tests

on:
  pull_request:
    paths:
      - "smoke-tests/images/quarkus/**"
      - ".github/workflows/pr-smoke-test-quarkus-images.yml"

jobs:
  build:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      project: ":smoke-tests:images:quarkus"
      cache-read-only: true
      # Quarkus 2.0+ does not support Java 8
      skip-java-8: true
