name: PR build gRPC images for smoke tests

on:
  pull_request:
    paths:
      - "smoke-tests/images/grpc/**"
      - ".github/workflows/pr-smoke-test-grpc-images.yml"

jobs:
  build:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      project: ":smoke-tests:images:grpc"
      cache-read-only: true
