name: Publish Security Manager test app images for smoke tests

on:
  push:
    paths:
      - "smoke-tests/images/security-manager/**"
      - ".github/workflows/publish-smoke-test-security-manager-images.yml"
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      project: ":smoke-tests:images:security-manager"
      publish: true

  workflow-notification:
    needs:
      - publish
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.publish.result == 'success' }}
